refactor topsecret

diff --git a/topsecret b/topsecret
--- a/topsecret
+++ b/topsecret
@@ -1,136 +1,160 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-# utility to crypt/decrypt a folder to a file.
+# utility to create/extract a gpg crypted gzipped tar archive.
+
+
+#
+# Bash settings
+# 
+set -o errexit   # abort on nonzero exitstatus
+set -o nounset   # abort on unbound variable
+set -o pipefail  # don't hide errors within pipes
+
+# outputs each line of script as it executes it
+if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi
+
+#
+# Constants
+#
+readonly CMDNAME="${0##*/}" 
+
+TAR_COMPRESSION="--gzip"
+
+TAR_CREATE_OPT=("${TAR_COMPRESSION}")
+TAR_EXTRACT_OPT=("${TAR_COMPRESSION}" --preserve-permissions --keep-old-files)
+
+# GPG_OPT=(--batch --passphrase "PASSPHRASE") # dev mode
+GPG_OPT=()
+
+DEFAULT_EXT=".tar.gz.gpg"
+
+#
+# Functions
 #
 
-# gpg options
-#GPG_OPT='--batch --passphrase "PASSPHRASE"'
-GPG_OPT=
 
-CRYPTED_FILE=
-PLAIN_FOLDER=
-OP_CRYPT=0
-OP_DECRYPT=0
-
-
-# Usage info
-show_help() {
+# Print usage informations
+usage() {
 	cat << EOF
-${0##*/}: utility to crypt/decrypt a folder to a file.
+${CMDNAME}: utility to create/extract a gpg crypted gzipped tar archive.
 
-Usage: ${0##*/} -c|--crypt <source plain dir> <dest crypted file>
-       ${0##*/} -d|--decrypt <source crypted file> <dest plain dir>
-       ${0##*/} -h|--help
+Usage: 
+  ${CMDNAME} crypt   file item [item...]
+  ${CMDNAME} decrypt file [folder]
 
-In crypt mode, save a folder content in a new file crypted with
-symmetric cipher using a passphrase.
-In decrypt mode, restore the plain content to a new folder.
+Aliases:
+  c, -c, --crypt for crypt 
+  d, -d, --decrypt for decrypt 
+
 Exit with error in case destination file or folder already exists.
 EOF
 }
 
 
-# Tar the folder content and crypt the tar file.
-crypt_dir() {
-	if [ -e "$CRYPTED_FILE" ]
-	then
-		# error if crypted file already exists
-		echo "Destination file \"$CRYPTED_FILE\" already exists!" 1>&2
-		exit 1
-	elif [ ! -d "$PLAIN_FOLDER" ]
-	then
-		# error if source folder not exists
-		echo "Source folder \"$PLAIN_FOLDER\" not found!" 1>&2
-		exit 1
-	else
-		# compress and crypt source folder
-		tar -czpf - -C "$PLAIN_FOLDER" . | gpg $GPG_OPT --symmetric -o "$CRYPTED_FILE"
-	fi
+# Print message to stdout
+#
+# Usage:
+#    log STRING [STRING...]
+# Arguments:
+#    STRING : message to print
+#
+log() {
+	printf '%s\n' "$@"
 }
 
-# Decrypt the archive and untar it to the destination folder
-decrypt_file() {
 
-	if [ ! -e "$CRYPTED_FILE" ]
-	then
-		# error if crypted file not exists
-		echo "Source file \"$CRYPTED_FILE\" not found!" 1>&2
-		exit 1
-	elif [ -d "$PLAIN_FOLDER" ]
-	then
-		# error if destination folder already exists
-		echo "Destination folder \"$PLAIN_FOLDER\" already exists!" 1>&2
-		exit 1
-	else
-		# decrypt and decompress source file
-		mkdir "$PLAIN_FOLDER"
-		gpg $GPG_OPT -d $CRYPTED_FILE | tar -xzpf - -C "$PLAIN_FOLDER"
-	fi
+# Print message to stderr and exit 1
+#
+# Usage:
+#    die STRING [STRING...]
+# Arguments:
+#    STRING : message to print
+#
+die() {
+	printf '%s: %s\n' "${CMDNAME}" "$@" >&2
+	exit 1
 }
 
-# -----------------------------------------------------------------------------
-# Parse command line arguments. Check for errors.
 
-OPTS=`getopt -o cdh --long help,crypt,decrypt -n 'parse-options' -- "$@"`
+# Tar the items and crypt the tar file
+#
+# Usage:
+#    create_crypted_tar FILE ITEM [ITEM...]
+# Arguments:
+#    FILE : destination gpg crypted gzipped tar file
+#    ITEM : one or more source file/dir to archive
+#
+create_crypted_tar() {
+    [[ $# -eq 0 ]] && die "destination file must be specified"
+	local file="${1}"
+	if [[ "${file##*/}" != *"."* ]]; then
+		file="${file}${DEFAULT_EXT}"
+	fi
 
-if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi
+	[[ -e "${file}" ]] && die "destination file already exists: \"${file}\""
 
+    shift
 
-#echo "$OPTS"
+    [[ $# -eq 0 ]] && die "at least one item to archive must be specified"
+	local items=("$@")
 
-eval set -- "$OPTS"
+    tar cf - "${TAR_CREATE_OPT[@]}" "${items[@]}" | gpg "${GPG_OPT[@]}" --symmetric -o "${file}"
 
-
-while true; do
-case "$1" in
-	-h | --help )    show_help; exit 0 ;;
-	-c | --crypt ) OP_CRYPT=1; shift ;;
-	-d | --decrypt ) OP_DECRYPT=1; shift ;;
-	-- ) shift; break ;;
-	* ) break ;;
-esac
-done
-
-# check OPERATION: crypt or decrypt
-OP=$(( OP_CRYPT + OP_DECRYPT ))
-
-if (( OP == 2 )) ;
-then
-	echo "Error: crypt or decrypt must be given, not both" >&2 ; exit 1
-elif (( OP == 0 )) ;
-then
-	echo "Error: crypt or decrypt must be given" >&2 ; exit 1
-fi
-
-if (( OP_CRYPT == 1 )) ;
-then
-	PLAIN_FOLDER=$1
-	CRYPTED_FILE=$2
-else
-	CRYPTED_FILE=$1
-	PLAIN_FOLDER=$2
-fi
+	log "created gpg crypted gzipped tar file: \"${file}\""
+}
 
 
-# check FILE
-if [[ -z "$CRYPTED_FILE"  ]] ;
-then
-	echo "Error: FILENAME must be given" >&2 ; exit 1
-fi
+# Decrypt the archive and untar it
+#
+# Usage:
+#    extract_crypted_tar FILE [ FOLDER ]
+# Arguments:
+#    FILE   : source gpg crypted gzipped tar file
+#    FOLDER : destination folder. If missing, use the name of the file (without extension)
+#
+extract_crypted_tar() {
+    [[ $# -eq 0 ]] && die "source file must be specified"
+	local file="${1}"
+	local folder="${2:-}"
+
+    if [[ -z "${folder}" ]]; then
+        # get folder name from file
+	    folder="${file##*/}"  # trim path
+	    folder="${file%%.*}"  # trim extension
+    fi
+
+	[[ -e "${folder}" ]] && die "destination folder already exists: \"${folder}\""
+
+	gpg "${GPG_OPT[@]}" --decrypt "${file}" | tar xf - "${TAR_EXTRACT_OPT[@]}" --one-top-level="${folder}"
+
+	log "gpg crypted gzipped tar file \"${file}\" extracted to folder \"${folder}\""
+}
 
 
-# check FOLDER
-if [[ -z "$PLAIN_FOLDER" ]] ;
-then
-	echo "Error: FOLDER must be given" >&2 ; exit 1
-fi
 
 
-# -----------------------------------------------------------------------------
+main() {
+	case ${1:-} in
+		h|help|-h|--help)
+			usage
+			;;
+		c|crypt|-c|--crypt)
+			shift
+			create_crypted_tar "$@"
+			;;
+		d|decrypt|-d|--decrypt)
+			shift
+			extract_crypted_tar "$@"
+			;;
+		*)
+			if (($# == 0)) ; then
+				usage
+			else
+				die "unknown command \"$1\"."
+			fi
+			;;
+	esac
 
-if (( OP_CRYPT == 1 )) ;
-then
-	crypt_dir
-else
-	decrypt_file
-fi
+}
+
+main "$@" 
